services:
  Sysacad:
    image: mysql:8.0
    container_name: db-sysacad
    environment:
      - 'MYSQL_ROOT_PASSWORD=123456789'
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  auth-service:
    build: ./auth-service
    container_name: auth-service
    depends_on:
      - Sysacad
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://Sysacad:3306/alumnos-sysacad
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456789
    ports:
      - "8080:8080"

  inscriptions-service:
    build: ./materias-alumnos
    container_name: inscriptions-service
    depends_on:
      - Sysacad
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://Sysacad:3306/inscripciones-materias
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456789
    ports:
      - "8081:8081"