services:
  sysacad-materias-service:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://Sysacad:3306/materias
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456789
    ports:
      - "8083:8083"
